"""create social post tables

Revision ID: 306e706eb31b
Revises: 
Create Date: 2026-07-28 06:48:17.702068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '306e706eb31b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('social_post_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('story_description', sa.Text(), nullable=True),
    sa.Column('hashtags', sa.JSON(), nullable=True),
    sa.Column('settings_snapshot', sa.JSON(), nullable=True),
    sa.Column('news_results', sa.JSON(), nullable=True),
    sa.Column('media_filename', sa.String(), nullable=True),
    sa.Column('publish_status', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_post_history_id'), 'social_post_history', ['id'], unique=False)
    op.create_index(op.f('ix_social_post_history_user_id'), 'social_post_history', ['user_id'], unique=False)
    op.create_table('social_post_template_prefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('store', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_post_template_prefs_id'), 'social_post_template_prefs', ['id'], unique=False)
    op.create_index(op.f('ix_social_post_template_prefs_user_id'), 'social_post_template_prefs', ['user_id'], unique=True)
    op.create_table('social_post_publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('history_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('external_url', sa.String(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['history_id'], ['social_post_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_post_publications_history_id'), 'social_post_publications', ['history_id'], unique=False)
    op.create_index(op.f('ix_social_post_publications_id'), 'social_post_publications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_post_publications_id'), table_name='social_post_publications')
    op.drop_index(op.f('ix_social_post_publications_history_id'), table_name='social_post_publications')
    op.drop_table('social_post_publications')
    op.drop_index(op.f('ix_social_post_template_prefs_user_id'), table_name='social_post_template_prefs')
    op.drop_index(op.f('ix_social_post_template_prefs_id'), table_name='social_post_template_prefs')
    op.drop_table('social_post_template_prefs')
    op.drop_index(op.f('ix_social_post_history_user_id'), table_name='social_post_history')
    op.drop_index(op.f('ix_social_post_history_id'), table_name='social_post_history')
    op.drop_table('social_post_history')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
